services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - php
    networks:
      - internal
    volumes:
      - ./api/:/var/www/html/API/v1

  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./api/:/var/www/html/API/v1

networks:
  internal:
    driver: bridge